USUARIO_ADMINPORT = "matheus"
MINHA_SENHAPORT = "suasenha"

# Novas chaves para o GitHub
GITHUB_TOKEN = "ghp_seu_token_gerado_no_github_aqui"
GITHUB_REPO = "seu-usuario/nome-do-repositorio"
GITHUB_BRANCH = "main" # ou "master"
